project:
  type: website

execute:
  freeze: auto

website:
  title: "Xuefeng Xu"
  description: "Xuefeng Xu's Homepage"
  favicon: "img/goose.png"
  site-url: https://xuefeng-xu.github.io
  repo-url: https://github.com/xuefeng-xu/xuefeng-xu.github.io
  repo-branch: master
  repo-actions: [source]
  open-graph: true
  twitter-card: true
  google-analytics: "G-9QXY2VK8LM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: teach/index.qmd
        text: Teaching
      - href: blog/index.qmd
        text: Blog
      - href: cv.qmd
        text: CV
      - href: misc/index.qmd
        text: Misc.
    right:
      - icon: rss
        href: blog/index.xml

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(52, 152, 219)
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left
    html-math-method: katex
    link-external-newwindow: true
    crossrefs-hover: false
